version: '2'
networks:
   bridge:

services:

  peer5:
    container_name: peer5
    image: sfhackfest22017/fabric-peer:x86_64-0.7.0-snapshot-c7b3fe0
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=peer0
      - CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_ID=peer5
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_DISCOVERY_ROOTNODE=peer0:7051
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer:7050
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_GOSSIP_IGNORESECURITY=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer

    ports:
      - 8059:7051
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./tmp/peer2:/etc/hyperledger/fabric/msp/sampleconfig
    networks:
      - bridge


